# Generated by Django 5.1 on 2024-08-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_evento_idevento_remove_funcao_idfuncao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('rebotes', models.IntegerField(default=0)),
                ('faltas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeJogador', models.CharField(max_length=150)),
                ('numeroCamisa', models.IntegerField()),
                ('posicao', models.CharField(max_length=50)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dataNascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPartida', models.DateField()),
                ('localPartida', models.CharField(max_length=200)),
                ('pontosCasa', models.IntegerField(default=0)),
                ('pontosVisitante', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTime', models.CharField(max_length=150)),
                ('cidadeTime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTorneio', models.CharField(max_length=100)),
                ('descricaoTorneio', models.CharField(max_length=300)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('times', models.ManyToManyField(related_name='torneios', to='app.time')),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTreinador', models.CharField(max_length=150)),
                ('telefoneTreinador', models.CharField(max_length=11)),
                ('dataNascimentoTreinador', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='instrumentistaInstrumento',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='tipoInstrumento',
        ),
        migrations.RemoveField(
            model_name='pequenogrupo',
            name='liderPequenoGrupo',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='anfitriaoVisita',
        ),
        migrations.RemoveField(
            model_name='ministerio',
            name='membrosMinisterio',
        ),
        migrations.RemoveField(
            model_name='pequenogrupo',
            name='membrosPequenoGrupo',
        ),
        migrations.RemoveField(
            model_name='ministerio',
            name='liderMinisterio',
        ),
        migrations.AddField(
            model_name='estatistica',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='app.jogador'),
        ),
        migrations.AddField(
            model_name='estatistica',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='app.partida'),
        ),
        migrations.AddField(
            model_name='partida',
            name='timeCasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='app.time'),
        ),
        migrations.AddField(
            model_name='partida',
            name='timeVisitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='app.time'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='app.time'),
        ),
        migrations.AddField(
            model_name='time',
            name='treinadorTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='app.treinador'),
        ),
        migrations.DeleteModel(
            name='Funcao',
        ),
        migrations.DeleteModel(
            name='Instrumento',
        ),
        migrations.DeleteModel(
            name='TipoInstrumento',
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
        migrations.DeleteModel(
            name='PequenoGrupo',
        ),
        migrations.DeleteModel(
            name='Membro',
        ),
        migrations.DeleteModel(
            name='Ministerio',
        ),
    ]
